core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name='core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('login/', views.login_user, name='login'),
    path('account_info/', views.account_info, name='account_info'),
    path('profile/', views.dashboard, name='account'),
    path('logout/', views.logout_user, name='logout'),
    path('transfer/', views.transfer, name = 'transfer'),
    path('confirmation/', views.confirm_transaction, name='confirm_transaction'),
]

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':'Your Email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    


class AccountInformationForm(forms.Form):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'phone', 'transaction_pin']
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your Firstname',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your Lastname',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    phone = forms.IntegerField(widget=forms.NumberInput(attrs={
        'placeholder':'Your Phone number',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    transaction_pin = forms.IntegerField(widget=forms.TextInput(attrs={
        'placeholder':'Your Transaction Pin',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class MakeTransfer(forms.Form):
    class Meta:
        model = User
        fields = ['account_number', 'amount']
    account_number = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder":"The receiver's account number",
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    amount = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder":"The amount to transfer",
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class ConfirmTransactionPin(forms.Form):
    transaction_pin = forms.CharField(
        widget=forms.TextInput(attrs={
            "placeholder": "Your transaction pin",
            'class': 'w-full py-4 px-6 rounded-xl'
        })
    )

core/templates/core/account_info.html
{% extends 'core/base.html' %}

{% block title %}User Registation Info{% endblock title %}
{% block content %}
<div class='w-1/2 p-6 my-6 mx-auto bg-gray-100 rounded-xl'>
    <h1 class='mb-6 text-3xl'>Sign Up</h1>
    <form method='POST' action='.'>
        {% csrf_token %}

        {{ form.non_field_errors }}

        <label for="first_name" class='inline-block mb-2'>Firstname</label><br/>
        <input type="text" name="first_name" placeholder="Firstname" maxlength="30" minlength="2" required id="id_first_name"><br/>
        {{form.first_name.errors}}<br/>
        <label for="last_name" class='inline-block mb-2'>Lastname</label><br/>
        <input type="text" name="last_name" placeholder="Lastname" maxlength="30" minlength="2" required id="id_last_name"><br/>
        {{form.last_name.errors}}<br/>
        <label for="phone" class='inline-block mb-2'>Phone</label><br/>
        <input type="text" name="phone" placeholder="Phone" maxlength="14" minlength="5" required id="id_phone"><br/>
        {{form.phone.errors}}
        <label for="phone" class='inline-block mb-2'>Transaction pin</label><br/>
        <input type="text" name="transaction_pin" placeholder="Transaction pin" maxlength="4" minlength="4" required id="id_pin"><br/>
        {{form.phone.errors}}

        {% if form.errors or form.non_field_errors %}
            <div class='mb-3 p-6bg-red-100 rounded-xl'>
                {% for field in form  %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button type="submit" class='py-4 px-8 text-lg bg-red-500 hover:bg-red-700 rounded-xl text-white'>continue</button><br/><br/>
    </form>
</div>
{% endblock content %}

core/templates/core/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1.0'>

        <script src='https://cdn.tailwindcss.com'></script>
        <title>{% block title %}{% endblock  %} | Rhiemann</title> 
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Black+Ops+One&display=swap" rel="stylesheet">
        <!--<link rel="icon" type="image/x-icon" href="media/rhiemann.png">-->

        <style>
            .head{
                font-family: 'Black Ops One', cursive;
                font-size: 75px;
            }
        </style>
    </head>
    <body>
        <nav class='py-6 px-6 flex justify-between items-center border-b border-gray-200'>
            <a href='/' class='text-x font-semibold'>Rhiemann Bank</a>
            <div class='space-x-6'>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'core:transfer' %}" class='px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700'>Make Transfer</a>
                    <a href="{% url 'core:account' %}" class='px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700'>Dashboard</a>
                    <a href="#" class='px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700'>Transactions</a>
                    <a href="{% url 'core:logout' %}" class='px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700'>Logout</a>
                {% else %}
                    <a href="{% url 'core:account_info' %}" class='px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700'>Sign Up</a>
                    <a href="{% url 'core:login' %}" class='px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700'>Log in</a>
                    
                {% endif %}
                
                
            </div>
        </nav>

        <div class='px-6 py-6'>
            {% block content %}
            
            {% endblock  %}
        </div>


        <footer class='py-6 px-6 flex justify-between bg-gray-800'>
            <div class='w-2/3 pr-10'>
                <h3 class='mb-5 font-semibold text-gray-400'>About</h3>
                <p class='text-lg text-gray-500'>Rhiemann Bank App created with Django, HTML, Tailwind/CSS.</p>

            </div>
            <div class='w-1/3'>
                <h3 class='mb-5 font-semibold text-gray-400'>Menu</h3>

                <ul class='space-y-2'>
                    <li><a href='#' class='text-lg text-teal-500 hover:text-teal-700'>About</a></li>
                    <li><a href="#" class='text-lg text-teal-500 hover:text-teal-700'>Contact</a></li>
                    <li><a href='#' class='text-lg text-teal-500 hover:text-teal-700'>Privacy Policy</a></li>
                    <li><a href='#' class='text-lg text-teal-500 hover:text-teal-700'>Terms of Use</a></li>
                </ul>
            </div>
        </footer>
    </body>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock title %}

{% block content %}
    <p class="head">Rhiemann Bank.<br>Super Fast.<br>Reliable.<br>Secure.<p>
{% endblock  %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log In{% endblock title %}

{% block content %}
    <div class='w-1/2 p-6 my-6 mx-auto bg-gray-100 rounded-xl'>
        <h1 class='mb-6 text-3xl'>Log In</h1>

        <form method='POST' action='.'>
            {% csrf_token %}

            {{ form.non_field_errors }}

            <div class='mb-3'>
                <label class='inline-block mb-2'>Username</label><br>
                {{ form.username }}
            </div>

            

            <div class='mb-3'>
                <label class='inline-block mb-2'>Password</label><br>
                {{ form.password }}
            </div>

            

            {% if form.errors or form.non_field_errors %}
                <div class='mb-3 p-6bg-red-100 rounded-xl'>
                    {% for field in form  %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class='py-4 px-8 text-lg bg-red-500 hover:bg-red-700 rounded-xl text-white'>Submit</button>
        </form>

    </div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign Up{% endblock title %}

{% block content %}
    <div class='w-1/2 p-6 my-6 mx-auto bg-gray-100 rounded-xl'>
        <h1 class='mb-6 text-3xl'>Sign Up</h1>

        <form method='POST' action='.'>
            {% csrf_token %}

            {{ form.non_field_errors }}

            
            <div class='mb-3'>
                <label class='inline-block mb-2'>Username</label><br>
                {{ form.username }}
            </div>

            <div class='mb-3'>
                <label class='inline-block mb-2'>Email</label><br>
                {{ form.email }}
            </div>

            <div class='mb-3'>
                <label class='inline-block mb-2'>Password</label><br>
                {{ form.password1 }}
            </div>

            <div class='mb-3'>
                <label class='inline-block mb-2'>Repeat Password</label><br>
                {{ form.password2 }}
            </div>

           

            {% if form.errors or form.non_field_errors %}
                <div class='mb-3 p-6bg-red-100 rounded-xl'>
                    {% for field in form  %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class='py-4 px-8 text-lg bg-red-500 hover:bg-red-700 rounded-xl text-white'>Submit</button>
        </form>

    </div>
{% endblock %}