core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name='core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('login/', views.login_user, name='login'),
    path('account_info/', views.account_info, name='account_info'),
    path('profile/', views.dashboard, name='account'),
    path('logout/', views.logout_user, name='logout'),
    path('transfer/', views.transfer, name = 'transfer'),
    path('confirmation/', views.confirm_transaction, name='confirm_transaction'),
]

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':'Your Email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    


class AccountInformationForm(forms.Form):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'phone', 'transaction_pin']
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your Firstname',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your Lastname',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    phone = forms.IntegerField(widget=forms.NumberInput(attrs={
        'placeholder':'Your Phone number',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    transaction_pin = forms.IntegerField(widget=forms.TextInput(attrs={
        'placeholder':'Your Transaction Pin',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class MakeTransfer(forms.Form):
    class Meta:
        model = User
        fields = ['account_number', 'amount']
    account_number = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder":"The receiver's account number",
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    amount = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder":"The amount to transfer",
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class ConfirmTransactionPin(forms.Form):
    transaction_pin = forms.CharField(
        widget=forms.TextInput(attrs={
            "placeholder": "Your transaction pin",
            'class': 'w-full py-4 px-6 rounded-xl'
        })
    )

core/templates/transfer/confirm-transfer.html
{% extends 'core/base.html' %}

{% block title %}Enter Transaction pin{% endblock title %}

{% block content %}
    <p>You are about to send {{amount}} to {{reciever_account}} || {{reciever_name}}</p>

    <form method="POST" action=".">
        {% csrf_token %}
        <input type="text" placeholder="Transaction pin" name="transaction_pin" maxlength="4" required id="id_pin"><br/>
        {{form.account.errors}}<br/>
        <button type="submit">Send</button>
    </form>
{% endblock content %}

core/templates/transfer/make-transfer.html
{% extends 'core/base.html' %}

{% block title %}Transfer funds to a user{% endblock title %}

{% block content %}

<div class='w-1/2 p-6 my-6 mx-auto bg-gray-100 rounded-xl'>
    <h1 class='mb-6 text-3xl'>Send money</h1>
    {% for a in account %}
        <p>Account Balance: ${{a.account_balance}}</p>
    {% endfor %}
    <form method='POST' action='.'>
        {% csrf_token %}

        {{ form.non_field_errors }}
        <div class='mb-3'>
            <input type="text" placeholder="Account Number" name="account_number" maxlength="15" required id="id_account"><br/>
            {{form.account.errors}}<br/>
        </div>


        <div class='mb-3'>
            <input type="text" placeholder="Amount" name="amount" minlength="1" required id="id_amount"><br/>
            {{form.amount.errors}}<br/>
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class='mb-3 p-6bg-red-100 rounded-xl'>
                {% for field in form  %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button type='submit' class='py-4 px-8 text-lg bg-red-500 hover:bg-red-700 rounded-xl text-white'>Continue</button>
    </form>
</div>

{% endblock content %}